blank_issues_enabled: false
contact_links: darrelsaina2000@gmail.com
  - name: Darrel S
    url: https://discordapp.com/invite/DThbZ7z
    about: Been having the issue "Failed to open sdmc:/atmosphere/package3! I don't know what else to do I downloaded the latest software, downloaded the Training Mods, and checked my switch to see if it was hackable and it was I don't if I can send pictures on here but, if you could respond back to me by email would be happy to send you pictures of my setuo and files downloaded. Thanks!
